In [1]:
import torch

In [2]:
t1 = torch.tensor([1,2,3])
t2 = torch.zeros(3,3)
t3 = torch.ones(2,2, dtype=torch.int32)
t4 = torch.rand(2,3)

print("Tensor from list:", t1)
print("Zero Tensor:\n", t2)
print("Ones Tensor:\n", t3)
print("Random Tensor:\n", t4)

# Data types
a = torch.tensor([1,2,3], dtype=torch.float32)
b = torch.tensor([1,2,3], dtype=torch.int32)

print("Float tensor:", a)
print("Int tensor:", b)

Tensor from list: tensor([1, 2, 3])
Zero Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor:
 tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
Random Tensor:
 tensor([[0.6059, 0.5806, 0.8294],
        [0.2271, 0.3953, 0.9150]])
Float tensor: tensor([1., 2., 3.])
Int tensor: tensor([1, 2, 3], dtype=torch.int32)


In [3]:
x = torch.tensor([10,20,30])
y = torch.tensor([1,2,3])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)


Addition: tensor([11, 22, 33])
Subtraction: tensor([ 9, 18, 27])
Multiplication: tensor([10, 40, 90])
Division: tensor([10., 10., 10.])


In [4]:
a = torch.tensor([[1,2,3], [4,5,6]])
b = torch.tensor([10,20,30])

print("Broadcasted Addition:\n", a + b)


Broadcasted Addition:
 tensor([[11, 22, 33],
        [14, 25, 36]])


In [5]:
t = torch.tensor([[1,2,3], [4,5,6]])

print("Element:", t[0,1])
print("Row:", t[1])
print("Column:", t[:,1])

Element: tensor(2)
Row: tensor([4, 5, 6])
Column: tensor([2, 5])


In [6]:
x = torch.arange(1,10)
print("Original:", x)

y = x.view(3,3)
print("Reshaped: ", y)

Original: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Reshaped:  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [7]:
x = torch.tensor(2.5, requires_grad=True)

y = x**3 + 2*x

y.backward()

print("Gradient dy/dx at x=2:", x.grad)


Gradient dy/dx at x=2: tensor(20.7500)


In [8]:
A = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
B = torch.tensor([[5,6],[7,8]], dtype=torch.float32)

# Matrix Addition
print("A + B:\n", A + B)

# Matrix Multiplication
print("\nA * B:\n", torch.matmul(A,B))

# Transpose
print("\nTranspose of A:\n", A.T)

# Determinant
print("\nDeterminant of A:", torch.det(A))

# Inverse
print("\nInverse of A:\n", torch.linalg.inv(A))

# Eigen values and vectors
eigenvalues, eigenvectors = torch.linalg.eig(A)
print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

# Norm
print("\nNorm:", torch.norm(A))

# Trace
print("\nTrace of A:", torch.trace(A))

# Rank of matrix
print("\nRank:", torch.linalg.matrix_rank(A))

# Solve AX = B
X = torch.linalg.solve(A, B)
print("\nSolution of AX = B:", X)




A + B:
 tensor([[ 6.,  8.],
        [10., 12.]])

A * B:
 tensor([[19., 22.],
        [43., 50.]])

Transpose of A:
 tensor([[1., 3.],
        [2., 4.]])

Determinant of A: tensor(-2.)

Inverse of A:
 tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

Eigenvalues: tensor([-0.3723+0.j,  5.3723+0.j])

Eigenvectors:
 tensor([[-0.8246+0.j, -0.4160+0.j],
        [ 0.5658+0.j, -0.9094+0.j]])

Norm: tensor(5.4772)

Trace of A: tensor(5.)

Rank: tensor(2)

Solution of AX = B: tensor([[-3., -4.],
        [ 4.,  5.]])


In [9]:
import torch.nn as nn

class Perceptron(nn.Module):
    def __init__(self):
        super(Perceptron, self).__init__()
        self.linear = nn.Linear(2,1)

    def forward(self,x):
        return torch.sigmoid(self.linear(x))

In [10]:
X = torch.tensor([[0,0],[0,1],[1,0],[1,1]], dtype=torch.float32)
Y_and = torch.tensor([[0],[0],[0],[1]], dtype=torch.float32)

model = Perceptron()
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

# Training
for epoch in range(2000):
    pred = model(X)
    loss = loss_fn(pred, Y_and)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print("AND Gate Output:")
print(model(X).round())

AND Gate Output:
tensor([[0.],
        [0.],
        [0.],
        [1.]], grad_fn=<RoundBackward0>)


In [11]:
Y_or = torch.tensor([[0],[1],[1],[1]], dtype=torch.float32)

model = Perceptron()

for epoch in range(2000):
    pred = model(X)
    loss = loss_fn(pred, Y_or)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print("OR Gate Output:")
print(model(X).round())

OR Gate Output:
tensor([[1.],
        [1.],
        [1.],
        [1.]], grad_fn=<RoundBackward0>)


In [12]:
X = torch.tensor([[0,0],[0,1],[1,0],[1,1]], dtype=torch.float32)
Y = torch.tensor([[0],[1],[1],[0]], dtype=torch.float32)

class XORModel(nn.Module):
    def __init__(self):
        super(XORModel, self).__init__()
        self.hidden = nn.Linear(2,4)  
        self.output = nn.Linear(4,1)

    def forward(self,x):
        x = torch.relu(self.hidden(x))  
        x = torch.sigmoid(self.output(x))
        return x

model = XORModel()

loss_fn = nn.BCELoss()             
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

# Training
for epoch in range(5000):
    pred = model(X)
    loss = loss_fn(pred, Y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print("XOR Output:")
print(model(X).round())


XOR Output:
tensor([[0.],
        [0.],
        [1.],
        [0.]], grad_fn=<RoundBackward0>)


In [16]:
import torch.optim as optim
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

df = pd.read_csv('house_price_full.csv')
X = df[['bedrooms', 'sqft_living']].values
y = df['price'].values.reshape(-1, 1)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
sc_x, sc_y = StandardScaler(), StandardScaler()
X_train_t = torch.tensor(sc_x.fit_transform(X_train), dtype=torch.float32)
y_train_t = torch.tensor(sc_y.fit_transform(y_train), dtype=torch.float32)
X_test_t = torch.tensor(sc_x.transform(X_test), dtype=torch.float32)


class MyNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.n1, self.n2 = nn.Linear(2, 1), nn.Linear(2, 1)
        self.out = nn.Linear(2, 1)
    def forward(self, x):
        h = torch.cat((torch.relu(self.n1(x)), torch.sigmoid(self.n2(x))), dim=1)
        return self.out(h)

model = MyNN()
opt = optim.Adam(model.parameters(), lr=0.01)
crit = nn.MSELoss()

for _ in range(1000):
    opt.zero_grad()
    crit(model(X_train_t), y_train_t).backward()
    opt.step()


model.eval()
with torch.no_grad():
    y_pred = sc_y.inverse_transform(model(X_test_t).numpy())
    
    r2 = r2_score(y_test, y_pred)

print(f"R-squared Score: {r2:.4f}")

R-squared Score: 0.3864
